import type { Exercise } from "../types";

export const exercises: Exercise[] = [
  {
    id: "goblet-squat",
    name: "Goblet squat",
    muscle: "Legs",
    equipment: "Dumbbells",
    sets: 3,
    reps: "8–12",
    rest: 90,
    instructions: [
      "Hold a dumbbell at your chest. Stand with your feet about shoulder-width apart.",
      "Sit between your hips, keeping your heels grounded and chest comfortably tall.",
      "Push through your whole foot to return to standing.",
    ],
    tip: "Choose a depth you can control without pain.",
  },
  {
    id: "bench-press",
    name: "Dumbbell bench press",
    muscle: "Chest",
    equipment: "Dumbbells",
    sets: 3,
    reps: "8–12",
    rest: 90,
    instructions: [
      "Lie on a bench with your feet planted, holding dumbbells above your chest.",
      "Lower slowly, with your elbows at a comfortable angle to your torso.",
      "Press upward smoothly without bouncing or locking forcefully.",
    ],
    tip: "Keep your shoulders supported by the bench.",
  },
  {
    id: "row",
    name: "Single-arm dumbbell row",
    muscle: "Back",
    equipment: "Dumbbells",
    sets: 3,
    reps: "10–12",
    rest: 75,
    instructions: [
      "Support one hand on a stable chair or bench and hinge at your hips.",
      "Pull the dumbbell toward your hip without rotating your torso.",
      "Lower with control. Complete the same reps on both sides.",
    ],
    tip: "Log the reps for one side; perform both sides.",
  },
  {
    id: "rdl",
    name: "Dumbbell Romanian deadlift",
    muscle: "Legs",
    equipment: "Dumbbells",
    sets: 3,
    reps: "8–12",
    rest: 90,
    instructions: [
      "Stand tall with dumbbells in front of your thighs and soft knees.",
      "Move your hips back while keeping the weights close to your legs.",
      "Stop at a comfortable hamstring stretch, then stand by bringing your hips forward.",
    ],
    tip: "Move from your hips, rather than rounding your back.",
  },
  {
    id: "press",
    name: "Dumbbell shoulder press",
    muscle: "Shoulders",
    equipment: "Dumbbells",
    sets: 3,
    reps: "8–12",
    rest: 90,
    instructions: [
      "Sit or stand tall with dumbbells at shoulder height.",
      "Press overhead through a comfortable range while keeping your ribs controlled.",
      "Lower slowly to your starting position.",
    ],
    tip: "A neutral palm position can feel more comfortable.",
  },
  {
    id: "lunge",
    name: "Reverse lunge",
    muscle: "Legs",
    equipment: "Bodyweight",
    sets: 3,
    reps: "8–10",
    rest: 60,
    instructions: [
      "Stand tall with your feet hip-width apart.",
      "Step one leg back and lower both knees through a comfortable range.",
      "Push through your front foot to return. Alternate sides.",
    ],
    tip: "Log reps per side, and use a support for balance if needed.",
  },
  {
    id: "squat",
    name: "Bodyweight squat",
    muscle: "Legs",
    equipment: "Bodyweight",
    sets: 3,
    reps: "10–15",
    rest: 60,
    instructions: [
      "Stand with feet about shoulder-width apart.",
      "Lower your hips with your heels grounded.",
      "Stand smoothly, keeping your knees moving in line with your toes.",
    ],
    tip: "Use a chair as a depth guide if helpful.",
  },
  {
    id: "pushup",
    name: "Incline push-up",
    muscle: "Chest",
    equipment: "Bodyweight",
    sets: 3,
    reps: "8–12",
    rest: 60,
    instructions: [
      "Place your hands on a stable elevated surface.",
      "Keep your body in a comfortable straight line as you lower your chest.",
      "Press away from the surface.",
    ],
    tip: "A higher surface makes the movement easier.",
  },
  {
    id: "bridge",
    name: "Glute bridge",
    muscle: "Legs",
    equipment: "Bodyweight",
    sets: 3,
    reps: "12–15",
    rest: 60,
    instructions: [
      "Lie on your back, knees bent and feet flat.",
      "Press into your feet and raise your hips without arching your back.",
      "Pause briefly, then lower with control.",
    ],
    tip: "Keep your ribs relaxed and movement controlled.",
  },
  {
    id: "deadbug",
    name: "Dead bug",
    muscle: "Core",
    equipment: "Bodyweight",
    sets: 3,
    reps: "8–10",
    rest: 45,
    instructions: [
      "Lie on your back with arms up and knees bent above your hips.",
      "Slowly extend one arm and the opposite leg as far as you can control.",
      "Return and alternate sides while breathing steadily.",
    ],
    tip: "Keep your lower back comfortable. Log reps per side.",
  },
  {
    id: "birddog",
    name: "Bird dog",
    muscle: "Core",
    equipment: "Bodyweight",
    sets: 3,
    reps: "8–10",
    rest: 45,
    instructions: [
      "Start on your hands and knees.",
      "Reach one arm and the opposite leg away from you.",
      "Keep your hips level, return, and alternate.",
    ],
    tip: "A smaller, controlled reach is better than a high leg lift.",
  },
  {
    id: "calf",
    name: "Standing calf raise",
    muscle: "Legs",
    equipment: "Bodyweight",
    sets: 3,
    reps: "12–15",
    rest: 45,
    instructions: [
      "Stand tall, using a stable support if needed.",
      "Raise your heels through a comfortable range.",
      "Pause, then lower slowly.",
    ],
    tip: "Avoid bouncing at the bottom.",
  },
  {
    id: "pulldown",
    name: "Lat pulldown",
    muscle: "Back",
    equipment: "Full gym",
    sets: 3,
    reps: "8–12",
    rest: 90,
    instructions: [
      "Sit with your thighs secured and take a comfortable grip.",
      "Pull the bar toward your upper chest, keeping your torso steady.",
      "Return slowly without shrugging.",
    ],
    tip: "Pull in front of your head, never behind your neck.",
  },
  {
    id: "legpress",
    name: "Leg press",
    muscle: "Legs",
    equipment: "Full gym",
    sets: 3,
    reps: "10–12",
    rest: 90,
    instructions: [
      "Set the seat so your back stays supported through your range.",
      "Lower the platform slowly, keeping your heels planted.",
      "Press out without forcefully locking your knees.",
    ],
    tip: "Use the machine’s safety stops and a controllable load.",
  },
  {
    id: "cable-row",
    name: "Seated cable row",
    muscle: "Back",
    equipment: "Full gym",
    sets: 3,
    reps: "10–12",
    rest: 75,
    instructions: [
      "Sit with feet supported and torso tall.",
      "Pull the handle toward your lower ribs without swinging.",
      "Extend your arms with control.",
    ],
    tip: "Keep your neck relaxed and shoulders away from your ears.",
  },
  {
    id: "curl",
    name: "Dumbbell curl",
    muscle: "Arms",
    equipment: "Dumbbells",
    sets: 3,
    reps: "10–12",
    rest: 60,
    instructions: [
      "Stand with your arms at your sides and palms forward.",
      "Curl the dumbbells without swinging your torso.",
      "Lower slowly through a comfortable range.",
    ],
    tip: "Keep your upper arms mostly still.",
  },
  {
    id: "lateral",
    name: "Lateral raise",
    muscle: "Shoulders",
    equipment: "Dumbbells",
    sets: 3,
    reps: "10–15",
    rest: 60,
    instructions: [
      "Hold light dumbbells at your sides with a slight bend in your elbows.",
      "Raise your arms out to the side to a comfortable height.",
      "Lower slowly, keeping your shoulders relaxed.",
    ],
    tip: "Start light. Control matters more than load.",
  },
  {
    id: "catcow",
    name: "Cat–cow",
    muscle: "Mobility",
    equipment: "Bodyweight",
    sets: 2,
    reps: "6–8",
    rest: 30,
    instructions: [
      "Begin on your hands and knees.",
      "Gently round your back as you exhale.",
      "Move toward a comfortable arch as you inhale.",
    ],
    tip: "Follow your breath and avoid forcing the range.",
  },
  {
    id: "rotation",
    name: "Side-lying rotation",
    muscle: "Mobility",
    equipment: "Bodyweight",
    sets: 2,
    reps: "6–8",
    rest: 30,
    instructions: [
      "Lie on your side with knees bent and arms in front.",
      "Rotate your upper arm and chest open through a comfortable range.",
      "Return slowly and repeat on the other side.",
    ],
    tip: "Let your eyes follow your hand. Log reps per side.",
  },
  {
    id: "wallslide",
    name: "Wall slide",
    muscle: "Mobility",
    equipment: "Bodyweight",
    sets: 2,
    reps: "8–10",
    rest: 30,
    instructions: [
      "Stand with your back close to a wall.",
      "Gently slide your arms upward without flaring your ribs.",
      "Return through a comfortable shoulder range.",
    ],
    tip: "Keep the motion pain-free; your arms need not touch the wall.",
  },
  {
    id: "stepup",
    name: "Step-up",
    muscle: "Legs",
    equipment: "Bodyweight",
    sets: 3,
    reps: "8–10",
    rest: 60,
    instructions: [
      "Choose a low, stable step.",
      "Place one foot fully on the step and stand up with control.",
      "Lower slowly and repeat on both sides.",
    ],
    tip: "Use a rail for balance if needed. Log reps per side.",
  },
  {
    id: "triceps",
    name: "Cable triceps pushdown",
    muscle: "Arms",
    equipment: "Full gym",
    sets: 3,
    reps: "10–12",
    rest: 60,
    instructions: [
      "Stand tall with your elbows close to your sides.",
      "Extend your elbows to press the handle down.",
      "Return slowly without moving your upper arms.",
    ],
    tip: "Use a comfortable grip and avoid leaning heavily into the weight.",
  },
];
exercises.push(
  {
    id: "floor-press",
    name: "Dumbbell floor press",
    muscle: "Chest",
    equipment: "Dumbbells",
    sets: 3,
    reps: "8–12",
    rest: 90,
    instructions: [
      "Lie on the floor with your knees bent and a dumbbell in each hand.",
      "Lower your upper arms gently to the floor, keeping wrists over elbows.",
      "Press up with control, then lower without bouncing.",
    ],
    tip: "Use a load you can safely get into and out of position.",
  },
  {
    id: "split-squat",
    name: "Dumbbell split squat",
    muscle: "Legs",
    equipment: "Dumbbells",
    sets: 3,
    reps: "8–12",
    rest: 90,
    instructions: [
      "Stand in a split stance with dumbbells at your sides.",
      "Bend both knees and lower straight down through a comfortable range.",
      "Press through your front foot to rise. Finish both sides.",
    ],
    tip: "Log reps per side. Start with bodyweight if balance limits you.",
  },
  {
    id: "dumbbell-deadlift",
    name: "Dumbbell deadlift",
    muscle: "Legs",
    equipment: "Dumbbells",
    sets: 3,
    reps: "8–12",
    rest: 90,
    instructions: [
      "Stand with dumbbells beside your legs and feet hip-width apart.",
      "Bend your hips and knees while keeping the weights close.",
      "Push through your feet to stand tall without leaning back.",
    ],
    tip: "The dumbbells do not have to reach the floor.",
  },
  {
    id: "hammer-curl",
    name: "Hammer curl",
    muscle: "Arms",
    equipment: "Dumbbells",
    sets: 3,
    reps: "10–15",
    rest: 60,
    instructions: [
      "Hold dumbbells by your sides with palms facing inward.",
      "Bend your elbows while keeping upper arms still.",
      "Lower slowly without swinging.",
    ],
    tip: "Keep your wrists comfortably straight.",
  },
  {
    id: "overhead-triceps",
    name: "Dumbbell triceps extension",
    muscle: "Arms",
    equipment: "Dumbbells",
    sets: 3,
    reps: "10–15",
    rest: 60,
    instructions: [
      "Hold one light dumbbell with both hands overhead.",
      "Bend your elbows to lower it behind your head through a comfortable range.",
      "Extend your elbows while keeping your torso still.",
    ],
    tip: "Choose a different triceps exercise if overhead movement is uncomfortable.",
  },
  {
    id: "chest-press-machine",
    name: "Machine chest press",
    muscle: "Chest",
    equipment: "Full gym",
    sets: 3,
    reps: "8–12",
    rest: 90,
    instructions: [
      "Adjust the seat so the handles are around chest height.",
      "Keep your back supported as you press the handles forward.",
      "Return slowly through a comfortable shoulder range.",
    ],
    tip: "Use the machine instructions to adjust the starting position.",
  },
  {
    id: "hamstring-curl",
    name: "Seated hamstring curl",
    muscle: "Legs",
    equipment: "Full gym",
    sets: 3,
    reps: "10–15",
    rest: 75,
    instructions: [
      "Adjust the machine so its pivot aligns with your knees.",
      "Secure the thigh pad, then curl your heels downward.",
      "Return slowly without letting the weights slam.",
    ],
    tip: "Follow the machine's setup guide before adding load.",
  },
  {
    id: "leg-extension",
    name: "Leg extension",
    muscle: "Legs",
    equipment: "Full gym",
    sets: 3,
    reps: "10–15",
    rest: 75,
    instructions: [
      "Adjust the seat and shin pad with your knees aligned to the pivot.",
      "Straighten your legs through a comfortable range.",
      "Lower slowly and keep your hips supported.",
    ],
    tip: "Choose a manageable load and avoid snapping your knees straight.",
  },
  {
    id: "face-pull",
    name: "Cable face pull",
    muscle: "Back",
    equipment: "Full gym",
    sets: 3,
    reps: "10–15",
    rest: 60,
    instructions: [
      "Set a rope attachment around face height and step back slightly.",
      "Pull toward your forehead with elbows moving comfortably outward.",
      "Return slowly while keeping your ribs controlled.",
    ],
    tip: "Use a light load that lets your shoulders move smoothly.",
  },
  {
    id: "standing-cable-press",
    name: "Standing cable chest press",
    muscle: "Chest",
    equipment: "Full gym",
    sets: 3,
    reps: "8–12",
    rest: 90,
    instructions: [
      "Set handles around chest height and take a stable split stance.",
      "Press forward while keeping your torso still.",
      "Return slowly until your elbows are comfortably beside your torso.",
    ],
    tip: "Start light and keep the movement controlled.",
  },
  {
    id: "kneeling-pushup",
    name: "Kneeling push-up",
    muscle: "Chest",
    equipment: "Bodyweight",
    sets: 3,
    reps: "8–12",
    rest: 60,
    instructions: [
      "Start with hands under your shoulders and knees on a comfortable surface.",
      "Keep a straight line from head to knees as you lower your chest.",
      "Press up smoothly without dropping your hips.",
    ],
    tip: "An incline push-up is another way to adjust the difficulty.",
  },
  {
    id: "full-pushup",
    name: "Push-up",
    muscle: "Chest",
    equipment: "Bodyweight",
    sets: 3,
    reps: "8–12",
    rest: 75,
    instructions: [
      "Start with hands beneath your shoulders and legs extended.",
      "Brace comfortably and lower your body as one unit.",
      "Press the floor away to return.",
    ],
    tip: "Switch to an incline if you cannot keep the movement controlled.",
  },
  {
    id: "pike-pushup",
    name: "Pike push-up",
    muscle: "Shoulders",
    equipment: "Bodyweight",
    sets: 3,
    reps: "6–10",
    rest: 90,
    instructions: [
      "Place your hands on the floor and lift your hips into an inverted V.",
      "Bend your elbows to lower your head toward a point between your hands.",
      "Press up through a comfortable shoulder range.",
    ],
    tip: "Keep pressure through your hands. Stop before your head touches the floor.",
  },
  {
    id: "single-leg-bridge",
    name: "Single-leg glute bridge",
    muscle: "Legs",
    equipment: "Bodyweight",
    sets: 3,
    reps: "8–12",
    rest: 60,
    instructions: [
      "Lie on your back with one foot planted and the other leg raised.",
      "Lift your hips while keeping your pelvis level.",
      "Lower slowly, then repeat on the other side.",
    ],
    tip: "Log reps per side. Return to two feet if your hips rotate.",
  },
  {
    id: "prone-y-raise",
    name: "Prone Y raise",
    muscle: "Back",
    equipment: "Bodyweight",
    sets: 2,
    reps: "8–12",
    rest: 45,
    instructions: [
      "Lie face down with your forehead supported by a folded towel.",
      "Reach your arms diagonally forward in a Y shape, thumbs up.",
      "Lift your arms a small distance, pause, and lower without arching your back.",
    ],
    tip: "This is light upper-back control work, not a substitute for a loaded row.",
  },
  {
    id: "reverse-snow-angel",
    name: "Prone arm sweep",
    muscle: "Back",
    equipment: "Bodyweight",
    sets: 2,
    reps: "8–12",
    rest: 45,
    instructions: [
      "Lie face down with your forehead comfortably supported.",
      "Hover your hands slightly and sweep your arms toward an overhead position.",
      "Reverse slowly through a comfortable range while keeping your ribs down.",
    ],
    tip: "Keep the movement small if your shoulders feel restricted.",
  },
  {
    id: "standing-hip-hinge",
    name: "Standing hip hinge",
    muscle: "Legs",
    equipment: "Bodyweight",
    sets: 2,
    reps: "10–15",
    rest: 45,
    instructions: [
      "Stand tall with soft knees and hands on your hips.",
      "Send your hips back as your torso tips forward.",
      "Stand by bringing your hips forward without rounding your back.",
    ],
    tip: "Practice the hinge pattern before adding external resistance.",
  },
  {
    id: "heel-tap",
    name: "Supine heel tap",
    muscle: "Core",
    equipment: "Bodyweight",
    sets: 3,
    reps: "8–12",
    rest: 45,
    instructions: [
      "Lie on your back with hips and knees bent about ninety degrees.",
      "Lower one heel to lightly touch the floor while keeping your trunk steady.",
      "Return and alternate sides while breathing normally.",
    ],
    tip: "Log reps per side and shorten the range if your back arches.",
  },
);
export const exerciseById = (id: string) => exercises.find((e) => e.id === id)!;
